name: Build
run-name: Build
on: [push]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Install SDL2 Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsdl2-dev

      - name: Install SDL2 
        run: |
          git clone https://github.com/libsdl-org/SDL
          cd SDL
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release --parallel
          sudo cmake --install . --config Release

      - name: "Clear SDL folder"
        run: sudo rm -rf ./SDL

      - uses: actions/checkout@v4
      - name: Run Build
        run: |
          chmod +x ./build.sh
          ./build.sh